# Generated by Django 5.0 on 2026-06-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('budget_avance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_imprevu', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('devis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devis_revu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='budget.poste')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='budget.projet'),
        ),
    ]
